### ISSUE TITLE
groupedFor group "datetime" - not work

### ISSUE THREAD

**Issue by typo3ua** [t3kit/theme_t3kit#248]
```
<f:section name="newsItemGrouped">
	<f:groupedFor each="{news}" as="newsItemGrouped" groupBy="yearOfDatetime" groupKey="currentYear">
		<div class="news-timeline-wrp">
		<h2 class="news-timeline__header">{currentYear}</h2>
			<f:for each="{newsItemGrouped}" as="newsItem" iteration="iterator">
				<f:cycle values="{0: 'odd', 1: 'even'}" as="cycle">
					<f:render section="newsTimeline" arguments="{newsItem: newsItem,settings:settings,iterator:iterator, val : cycle, startYear: news.0.yearOfDatetime}" />
				</f:cycle>
			</f:for>
		</div>
	</f:groupedFor>
</f:section>
```
I get error :
Fatal error: Call to a member function format() on null in /typo3temp/Cache/Code/news/tx_news_domain_model_news.php on line 373

  'News version' => '5.2.0'
   'typo3 version' => '7.6.0-8.9.99'

**Comment by pixelmatseriks** [comment]
Hi, seems like the field "Date & Time" (datetime) isn't set on a news record. It is mandatory, at least in news version 6.0.0, are the news records imported?

**Comment by typo3ua** [comment]
I'm using ...
'News version' => '5.2.0'
'typo3 version' => '7.6.0-8.9.99'

**Comment by pixelmatseriks** [comment]
The error is thrown when php tries to format datetime of a news record with property datetime not set ("format() on null").

There is an option to "Disable required date field" in extension configuration for news (extension manager) (also in 5.2.0). If set, the date field is not required and not filled automatically when creating a new record. By default it is unchecked and a datetime will be set when news records are created. The template layout "News list with timeline" should not be used when required date field is disabled, because it needs the date to group the news records.

**Comment by typo3ua** [comment]
How can I use it? What do I have to do? Can you give me an example?

**Comment by pixelmatseriks** [comment]
You need to make sure that none of your news records have the field datetime unset.
If you have access to the database you can run f.ex. `SELECT uid, pid, title FROM tx_news_domain_model_news WHERE datetime = 0;` to get the id:s and pid of news records where datetime is missing.
Or you could just check in TYPO3 BE listmode on the sysfolders containing news. If you click on the "News" header of the news listing you can add the "Date & Time" field to the list. Then it should be fairly easy to spot any news records without the datetime set.
