### ISSUE TITLE
FullWidthImage crops image

### ISSUE THREAD

**Issue by phathoang** [t3kit/theme_t3kit#50]
Default height is set to 400px so if the image is higher than 400px it gets cropped if the Editor doesn't manually enter the height in BE. I don't see a reason to limit it to 400px and crop it.

**Comment by phathoang** [comment]
Can we remove height or get the height from the original image instead of using settings.defaultHeight? I'm thinking if Height is needed in the srcset too, doesn't it also crop there if you set height?

**Comment by dmh** [comment]
About cropping, it should be, we should somehow crop this image, otherwise how we can create `320x200px` image from `1920x200px` image.

We are using `srcset` to have possibility use small images on mobile and tablets even if editor upload big image. Width of images for different screens is predefined in template `320, 640, 768, 1080, 1280, 1440, 1920px`, but height we can't predict, because it depend on design, so that's why we have special field to set image height. Not sure what you mean about _to get the height from the original image instead of using settings.defaultHeight_? Might be you could implement it and add PR to t3kit?

**Comment by phathoang** [comment]
TYPO3 should scale it correctly if we just set the width.
If I add a 1920x1080 regular image and set the widths, I will get the heights automatically:
1440 -> 810
1280 -> 720
1080 -> 608
768  -> 432
If those heights are used in the srcset, i.e. if we let TYPO3 scale it, then we won't get cropped images.

**Comment by dmh** [comment]
But what about if we want to have same height in all screens? 
Now it works like this, and I pretty sure that it is important feature of this element:
1920 -> 400
1440 -> 400
1280 -> 400
1080 -> 400
768 -> 400

(Original image 1920x1080 and height is 400px)

**Comment by phathoang** [comment]
Then it gets cropped and it's not good.
The feature is to be able to have full width image, not fixed height + crop.
The reason we created this image is because we don't want to allow regular images to be full width. This element should work the same as regular image but also be able to be full width. Regular images don't crop, so this shouldn't either.

**Comment by dmh** [comment]
ok, then we just need to expand template and add checkbox to enable/disable regular images without cropping

**Comment by phathoang** [comment]
I don't agree. The cropping is a bug for me because, as mentioned, this element should work like regular image without the width being limited to 600ish.
We should also check how it works if the editor does set a height..

**Comment by phathoang** [comment]
And this element origins from https://bitbucket.org/pixelant/privatleasing.com/src/21e53bff7defc2455ccba2f88b7a4aca9c4dfefa/fileadmin/templates/theme_t3kit/custom_content_elements/Resources/Private/Templates/CustomContentElements/FullWidthImage.html?at=master&fileviewer=file-view-default

Doesn't look like there's anything that crops the image.

**Comment by phathoang** [comment]
Also check how bad cropping is
http://rollco.typo3konsult.se/fileadmin/_processed_/c/0/csm_Rollco_Helsingborg_1d84fbcc3e.jpg
http://rollco.typo3konsult.se//fileadmin/_processed_/c/0/csm_Rollco_Helsingborg_70b9876bf0.jpg
even the name would have disappeared if it wasn't in the center

**Comment by dmh** [comment]
About Rollco I think it is bad example, because it is not screen-full-width image. 
About link to origins element, it is not supporting adaptive images, so this is different elements. I understand you about cropping, but without it this element will not work. If we remove height from this element we will have on mobile image `320x50px` from original `1920x300px`, but I want to have `320x300px` on mobile, because 50px height is too small.
Idea for this element is to use something like background images to make design more colorful and don't have big impact to performance, in this case good cropping is not so important.

But I understand you, so my suggestion is to create new element. What do you think about this solution?

**Comment by phathoang** [comment]
> About Rollco I think it is bad example, because it is not screen-full-width image. 

It's not a bad example because they had to use it to get the image full width in its container. 
I don't think fullwidthimage should be seen as "the image needs to be 1920px wide", if the image is 1800 then it should be good too. It's not called screenfullwidthimage either.

And even if it's full width, according to your cropping above:

> 1920 -> 400
> 1440 -> 400
> 1280 -> 400
> 1080 -> 400
> 768 -> 400

It will still get cropped badly.

> About link to origins element, it is not supporting adaptive images, so this is different elements.

It's different because it's done incorrectly with cropping. If the srcset was done with resizing we could have just switched the original element to the new one without problems, and even get the adaptive images, and all views would look the same.

> If we remove height from this element we will have on mobile image 320x50px from original 
> 1920x300px, but I want to have 320x300px on mobile, because 50px height is too small.

The original is NOT 1920 x 300, it is 1920x900. On mobile it will just be scaled down.. just like when u're on desktop and resize the window to the width of mobile, it will just **scale** down.

> Idea for this element is to use something like background images to make design more colorful and don't have big impact to performance, in this case good cropping is not so important.

Whose idea? The idea for this element should be from the origin of the element which doesn't crop the image. Rollco had to use it, and the cropping did cause problems. I don't see how this has anything to do with design, it's just a regular content element and we can use it anywhere.

**Comment by dmh** [comment]
I just want to repeat, that **I am not against your solution, I totally agree that we need it**, but I also want to keep it like it now, because I didn't find another way how we can implement full width image without container in start page, with the same height on desktop and mobile. `1920x200px - 320-200xp` I think that it is also needed feature.
But maybe the reason of this discussion is that I didn't find a way how to do it without cropping, so I will be glad if you help me.

**Comment by jozefspisiak** [comment]
Same height should be a checkbox we can implement. We can add also the default value into the extension configuration, in order not to break existing websites. Would this solution suit both of you?

**Comment by jozefspisiak** [comment]
also Dmytro, the ticket is about removing height limit for the full width images, which I agree with. So lets do a pull request on this one.

**Comment by dmh** [comment]
Add checkbox, but then remove height limit? Not sure that I understand you.

**Comment by dmh** [comment]
Could you explain your suggestion with more details? @jozefspisiak

**Comment by phathoang** [comment]
I don't see a reason to have same height, except in layout places (header, footer, menu etc) in which we already have custom HTML/CSS to do the same-height or whatever we want without using this element.

Adding a checkbox, maybe, but the element gets more complex than just like a regular image. I don't know if it will actually break, or fix existing websites. Maybe mark it as a breaking change and check all Fullwidthimage elements before upgrading.

Right now the adaptive images are wrong, i.e. if we're on desktop and scale the image down to mobile, it will not be the same as the image seen on a mobile because of the cropping. This will get fixed.
What could break is, if the image does get restricted by the default height of 400 and gets cropped and does look good. But there's cropping tool in BE too?

**Comment by jozefspisiak** [comment]
Remove height limit (or add override for this specific content element, which phat can set too 3000px) and add checkbox if you want to scale 1920x400 -> 768x400 or 1920x400 -> 768x160

**Comment by phathoang** [comment]
Btw isnt there a grid with bg element in t3kit? That one has a height of the image and crops because there can be content inside. At least thats how the original works.

**Comment by jozefspisiak** [comment]
This image should scale like phat suggests and shouldn't have height limit. Grid with bg image or elements with text should scale like Dmytro suggests. Dmytro please assign this to someone to create pull request.

**Comment by pixelmatseriks** [comment]
Closing issue, changed the way image is rendered in #201
