### ISSUE TITLE
Child Theme possibility

### ISSUE THREAD

**Issue by edekowalski** [t3kit/theme_t3kit#9]
Dear Developer,

in the Instruction Book for the Themes Extension. Is an Example for a "Child Theme" ist it possible to do the same for the theme_t3kit.

Best Regards
Ede

**Comment by dmh** [comment]
Our idea is to extend **theme_t3kit** for small sites, or create new extension based on **theme_t3kit** for big sites. We want to prevent using lot of dependencies, that's why everything included in one extension, except Front-End part, which we have in **felayout_t3kit** plugin.

So in our project we are not following this idea with "Child Theme" like it is implemented in TYPO3 Themes, but it is not too hard to do it. You always can create your new extension and use **theme_t3kit** as a parent with Back-End layouts, gridelements, custom content elements, etc.

Also one more thing. We have another way how to quickly modify design of **theme_t3kit**. It is our separated Front-End part (**felayout_t3kit**). We have possibility to change all js, css, icons, fonts without changing templates in main extension.

Thanks!
Dmytro

**Comment by edekowalski** [comment]
Dear Dmytro,

thank you for the answer and help.
Your T3kit Projekt is realy cool!

Best Regards
Ede
